FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PATH=/opt/bin:/opt/conda/bin:$PATH

RUN rm /etc/apt/sources.list.d/*

# update ubuntu packages
RUN apt-get update --fix-missing && \
    yes|apt-get upgrade && \
    DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y \
        wget \
        bzip2 \
        emacs-nox \
        git \
        tmux \
        less \
	    htop \
        openssh-server \
        make \
        g++ \
        gfortran-7 \
	software-properties-common\
        libboost-graph-dev && \
    rm -rf /bar/lib/apt/lists/*
    

WORKDIR /opt/bin
ENV PATH /opt/conda/envs/rundvc/bin:$PATH
ENV CONDA_DEFAULT_ENV rundvc

# install anaconda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda && \
    rm Miniconda3-latest-Linux-x86_64.sh && \
    conda config --add channels defaults && \
    conda config --add channels bioconda && \
    conda config --add channels conda-forge && \
    conda create -n rundvc python=3.9.0 -y &&\
    conda init bash && \
    /bin/bash -c "source activate rundvc" &&\
    conda install -c conda-forge -c anaconda pypy3.6 pigz parallel=20191122 zstd  -y && \
    conda install -c conda-forge -c anaconda -c bioconda whatshap=1.4 samtools=1.15.1 -y && \
    conda install -c conda-forge xz zlib bzip2 -y && \
    conda install -c conda-forge automake curl -y && \
    conda install -c conda-forge pytables && \
    pypy3 -m ensurepip && \
    pypy3 -m pip install mpmath==1.2.1 && \
    conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1  -c pytorch && \
    pip install  matplotlib && \
    pip install tensorboard  && \
    pip install torchmetrics && \
    pip install torchinfo && \
    pip install POT && \
    pip install scikit-learn && \
    #pip install scikit-learn && \
    pip install einops &&\
    pip install  cffi==1.14.4 pyyaml tqdm && \
    rm -rf /opt/conda/pkgs/* && \
    rm -rf /root/.cache/pip 
    


